# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'CD: Deploy build artifact to composite target'
run-name: 'Deploy to composite target: ${{ inputs.title-source }} ➡️ ${{ inputs.title-dest }}'

on:
  workflow_call:
    inputs:
      build-id:
        required: true
        type: string
      metadata-id:
        required: true
        type: string
      title-source:
        required: false
        type: string
        default: '?'
      title-dest:
        required: false
        type: string
        default: '?'

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      payload: ${{ steps.extract_json.outputs.environment }}
      version: ${{ steps.extract_json.outputs.version }}
    permissions:
      contents: read
      artifact-metadata: read
    name: Deploy to remote
    steps:
      # Mostly for the sake of the deploy action, which assumes a git directory is present
      - name: Checkout
        uses: actions/checkout@v7
        with:
          filter: 'blob:none' # only retrieve metadata
      
      # Get config payload
      - name: Download config payload
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ inputs.metadata-id }}
          path: payloads/build_metadata.json

      # Get environment, version, etc from config payload
      - name: Unpack payload inputs
        id: extract_json
        run: |
          payload='cat ./payloads/build_metadata.json'
          echo "payload_json=$payload" >> $GITHUB_OUTPUT
      
      - name: Parse payload inputs
        run: |
          echo "DEPLOY_ENV=${{ fromJson(steps.extract_json.outputs.payloadJson).deploy_env }}" >> $GITHUB_ENV
          echo "VERSION=${{ fromJson(steps.extract_json.outputs.payloadJson).version }}" >> $GITHUB_ENV

          echo "TARGET_REPO=${{ fromJson(steps.extract_json.outputs.payloadJson).target_repo }}" >> $GITHUB_ENV
          echo "TARGET_PATH=${{ fromJson(steps.extract_json.outputs.payloadJson).target_path }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ fromJson(steps.extract_json.outputs.payloadJson).pr_number }}" >> $GITHUB_ENV

          echo "COMMIT_HASH=${{ fromJson(steps.extract_json.outputs.payloadJson).commit_hash }}" >> $GITHUB_ENV
          echo "COMMIT_HEADER=${{ fromJson(steps.extract_json.outputs.payloadJson).commit_header }}" >> $GITHUB_ENV
          echo "BRANCH=${{ fromJson(steps.extract_json.outputs.payloadJson).branch }}" >> $GITHUB_ENV

          echo "environment=${{ fromJson(steps.extract_json.outputs.payloadJson).deploy_env }}" >> $GITHUB_OUTPUT
          echo "version=${{ fromJson(steps.extract_json.outputs.payloadJson).version }}" >> $GITHUB_OUTPUT

      - name: Echo inputs from payload
        run: |
          echo "Deploying commit $COMMIT_HASH"
          echo "Commit header: $COMMIT_HEADER"
          echo "Branch: $BRANCH"
          echo "Deploying version: $VERSION"
          echo "Environment: $DEPLOY_ENV"
          echo "Deploy target: /$TARGET_PATH @ $TARGET_REPO"
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ inputs.build-id }}
          path: build/

      - name: Deploy to composite repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          ssh-key: ${{ secrets.SSH_DEPLOY_HUB_SUBDOMAIN }}
          repository-name: ${{ env.TARGET_REPO }}
          target-folder: ${{ env.TARGET_PATH }}
          clean: $DEPLOY_ENV == 'production' # Set to false if deploying to a composite repository's root!
          git-config-name: "github-actions"
          git-config-email: "github-actions@github.com"

      - name: Post-deployment notification
        run: |
          if [[ "${{ env.DEPLOY_ENV }}" == "production" ]]; then
            echo "### Production build artifact uploaded! 🚀" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ env.DEPLOY_ENV }}" == "pr-staging" ]]; then
            echo "### Staging build artifact uploaded for PR #${{ env.PR_NUMBER }}! 🚀" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Staging build artifact uploaded! 🚀" >> $GITHUB_STEP_SUMMARY
            echo "To deploy to production, manually trigger the 'CI: Trigger staging deployment from main' workflow." >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: $DEPLOY_ENV" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deploy Target**: ${{ env.TARGET_PATH }} @ ${{ env.TARGET_REPO }}" >> $GITHUB_STEP_SUMMARY
          echo "- **URL (once live)**: https://hub.ciroh.org${{ env.BASE_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Deployment to GitHub Pages will be completed by the composite target repository, $TARGET_REPO." >> $GITHUB_STEP_SUMMARY