# Triggers a release build, which will proceed to production.

name: 'CI: Trigger production deployment from main'

on:
  push:
    branches:
    - main
    - test-deploy
    tags:
    - '*'
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Send repository dispatch'
      uses: peter-evans/repository-dispatch@v4
      with:
        repository: CIROH-UA/ciroh_hub
        event-type: build-main-for-production
        client-payload: '{"deploy_env": "production", "base_url": "/"}'
