# Triggers a CI/CD deployment from the main branch to staging.

name: 'CI: Trigger deployment from PR'
run-name: 'Trigger PR deployment from PR #${{ github.event.number }}'

on:
  pull_request:
    types: [labeled, reopened, synchronize]

env:
  STAGING_REPO: ${{ vars.COMPOSITE_TARGET_REPO }}
  STAGING_PATH: staging/

jobs:
#  debug-show-condition: 
#    runs-on: ubuntu-latest
#    steps:
#    - name: 'Echo conditions'
#      run: |
#        echo "Has flag: ${{ contains(github.event.pull_request.labels.*.name, 'preview on staging') }}"
#        echo "Is a labelling action: ${{ github.event.action == 'labeled' }}"
#        echo "Is applying flag: ${{ github.event.label.name == 'preview on staging' }}"

  prepare-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview on staging') && ( github.event.action != 'labeled' || github.event.label.name == 'preview on staging' ) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      params-id: ${{ steps.upload-params.outputs.artifact-id }}
      title-header: ${{ steps.fetch-commit-header.header }}
      title-destination: ${{ steps.set-destination.destination }}
      should-notify: ${{ vars.SILENCE_COMPOSITE_PR_MESSAGE != 'true' && github.event.action == 'labeled' && github.event.label.name == 'preview on staging' }}

    steps:
    - name: Set deployment target
      run: |
        echo "DEPLOY_ENV=pr-staging" >> $GITHUB_ENV
        echo "TARGET_REPO=$STAGING_REPO" >> $GITHUB_ENV
        echo "TARGET_PATH=${{ env.STAGING_PATH }}${{ github.event.number }}/" >> $GITHUB_ENV
        echo "Deploying to $STAGING_REPO as STAGING at path $STAGING_PATH${{ github.event.number }}/"
        echo "SOURCE_REPO=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_ENV
        echo "SOURCE_REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

    # Checkout to fetch commit header
    - name: Checkout
      uses: actions/checkout@v7
      with:
        repository: ${{ env.SOURCE_REPO }}
        ref: ${{ env.SOURCE_REF }}
        filter: 'blob:none' # only retrieve metadata
      
    - name: Fetch commit header
      run: |
        header="$(git log -1 --pretty=%B | head -n 1)"
        if [[ $header == *"\""* ]]; then
          echo "COMMIT_HEADER="(Unsafe header)" >> $GITHUB_ENV
        else
          echo "COMMIT_HEADER=${header}" >> $GITHUB_ENV
        fi
      # Credit to the solution at https://github.com/orgs/community/discussions/106392
    
    # Establish build params
    - name: Output build parameters
      run: |
        {"deploy_env": "${{ env.DEPLOY_ENV }}", "source_ref": "${{ env.SOURCE_REF }}", "source_repo": "${{ env.SOURCE_REPO }}", "target_repo": "${{ env.TARGET_REPO }}", "target_path": "${{ env.TARGET_PATH }}", "commit_header": "${{ env.COMMIT_HEADER }}", "pr_number": "${{ github.event.number }}"} > exports/pr_${{ github.event.number }}_build.json
        cat exports/pr_${{ github.event.number }}_build.json

    - name: Upload build parameters
      id: upload-params
      uses: actions/upload-artifact@v7
      with:
        name: pr_${{ env.github.event.number }}_build
        path: exports/pr_${{ github.event.number }}_build.json

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    needs: prepare-build
    permissions:
      artifact_metadata: write
      deployments: write
      metadata: read
      secrets: read
      variables: read
    outputs:
      build-id: ${{ steps.create-build.outputs.build-id }}
      metadata-id: ${{ steps.create-build.outputs.metadata-id }}
      title-destination: ${{ needs.prepare-build.outputs.title-destination }}
    steps:
    - name: Create build artifact
      id: create-build
      uses: ./.github/workflows/ci_build.yml
      with:
        config-id: ${{ needs.prepare-build.outputs.params-id }}
        title-source: main
        title-header: ${{ needs.prepare-build.outputs.title-header }}

  # For permission-management reasons, the next steps are handled in cd_receive_pr_artifact.